USE olist;

SET GLOBAL event_scheduler = ON;

DROP EVENT IF EXISTS salesEvent;

DELIMITER $$

CREATE EVENT salesEvent
ON SCHEDULE EVERY 5 MINUTE
STARTS CURRENT_TIMESTAMP
ENDS CURRENT_TIMESTAMP + INTERVAL 1 DAY
DO
	
		INSERT INTO messages SELECT CONCAT('sales updated at ',NOW());
    		CALL sales();
	
DELIMITER ;

